# Generated by Django 5.2.3 on 2025-07-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_alter_invoice_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
