# Generated by Django 5.2.3 on 2025-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturation", "0003_add_userprofile_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="subscription_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="subscription_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
